version: '3'
services:
  odoo:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
#      - LANG=C.UTF-8
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./customModules:/mnt/extra-addons
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
