version: '3'
services:
  web:
    build: './web/.'
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - BOX_IP=165.227.62.23
      - POSTGRES_PASSWORD=djangoAD
      - POSTGRES_USER=djangoAD
      - POSTGRES_DB_DJANGO = DjangoApplication
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=djangoAD
      - POSTGRES_USER=djangoAD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - django-db-data:/var/lib/postgresql/data/pgdata

volumes:
  django-db-data:
